# Imports

In [1]:
import pandas as pd
import requests

In [2]:
DATA_FOLDER = "C:/Users/User/Desktop/Nutrititon/FINAL FOOD DATASET"

# Data Prep

In [5]:
#inspect
dt1 = pd.read_csv(DATA_FOLDER + "/FOOD-DATA-GROUP1.csv")
dt2 = pd.read_csv(DATA_FOLDER + "/FOOD-DATA-GROUP2.csv")
dt3 = pd.read_csv(DATA_FOLDER + "/FOOD-DATA-GROUP3.csv")    
dt4 = pd.read_csv(DATA_FOLDER + "/FOOD-DATA-GROUP4.csv")

food_data = pd.concat([dt1, dt2, dt3, dt4], ignore_index=True)
food_data.tail()

,Unnamed: 0.1,Unnamed: 0,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
1668,227,227,muesli master crumble,124,2.4,1.000,19.800,8.500,4.5,0.042,...,0.000,0.000,0.000,0.0,0.000,0.00,0.0,0.000,0.000,9.300
1669,228,228,bran flakes,131,0.8,0.200,0.100,0.500,32.2,7.400,...,0.025,17.600,0.300,11.2,91.600,1.40,179.6,213.200,0.083,45.358
1670,229,229,nut cereal,245,5.9,1.000,3.900,0.500,46.2,17.200,...,75.600,0.200,10.300,39.0,1.000,106.80,134.4,0.066,3.000,156.500
1671,230,230,corn flakes,108,0.3,0.098,0.071,0.018,24.6,2.200,...,0.000,0.600,0.083,5.4,2.000,0.06,9.2,30.000,0.077,27.947
1672,231,231,corn grits dry,36,0.2,0.022,0.018,0.032,7.7,0.008,...,0.400,0.086,0.300,3.5,0.029,10.80,13.7,0.024,0.046,9.700

In [6]:
cols_to_drop = ['Unnamed: 0.1','Unnamed: 0']
food_data.drop(columns=cols_to_drop, inplace=True)

In [7]:
food_data

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,cream cheese,51,5.0,2.900,1.300,0.200,0.8,0.500,0.9,0.0,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,neufchatel cheese,215,19.4,10.900,4.900,0.800,3.1,2.700,7.8,0.0,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,requeijao cremoso light catupiry,49,3.6,2.300,0.900,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,ricotta cheese,30,2.0,1.300,0.500,0.002,1.5,0.091,1.5,0.0,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,cream cheese low fat,30,2.3,1.400,0.600,0.042,1.2,0.900,1.2,0.0,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1668,muesli master crumble,124,2.4,1.000,19.800,8.500,4.5,0.042,2.4,0.0,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,9.300
1669,bran flakes,131,0.8,0.200,0.100,0.500,32.2,7.400,4.0,7.3,...,0.025,17.600,0.300,11.200,91.600,1.400,179.6,213.200,0.083,45.358
1670,nut cereal,245,5.9,1.000,3.900,0.500,46.2,17.200,4.0,3.6,...,75.600,0.200,10.300,39.000,1.000,106.800,134.4,0.066,3.000,156.500
1671,corn flakes,108,0.3,0.098,0.071,0.018,24.6,2.200,1.7,0.8,...,0.000,0.600,0.083,5.400,2.000,0.060,9.2,30.000,0.077,27.947
1672,corn grits dry,36,0.2,0.022,0.018,0.032,7.7,0.008,0.7,0.4,...,0.400,0.086,0.300,3.500,0.029,10.800,13.7,0.024,0.046,9.700

In [12]:
food_data.to_csv(DATA_FOLDER + "/FOOD-DATA-FINAL.csv", index=False)

# Data Translation

In [3]:
food_data = pd.read_csv(DATA_FOLDER + "/FOOD-DATA-FINAL.csv")
food_data.head()

,food,Caloric Value,Fat,Saturated Fats,Monounsaturated Fats,Polyunsaturated Fats,Carbohydrates,Sugars,Protein,Dietary Fiber,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [4]:
class OllamaLLM:
    def __init__(self, model='llama3', host='http://localhost:11434'):
        self.model = model
        self.host = host

    def ask(self, message):
        response = requests.post(
            f"{self.host}/api/generate",
            json={
                "model": self.model,
                "prompt": message,
                "stream": False  # easier to handle non-streaming
            },
            timeout=120
        )
        response.raise_for_status()
        return response.json()

    def summarize(self, message):
        result = self.ask(message)
        return result.get('response', '')

In [5]:
# translate to portuguese with llama
# Use whatever model you have installed


llm_ollama = OllamaLLM(model='llama3')  # or 'mistral', 'phi3', etc.

# Test
answer = llm_ollama.summarize("What is the capital of France?")
print(answer)

The capital of France is Paris.

In [6]:
def translate_to_portuguese(text):
    prompt = f"In the context of nutrition and nutritional values, translate the following text to Portuguese:\n\n{text}. One sentence only, no explanations."
    return llm_ollama.summarize(prompt)

In [7]:
cols = food_data.columns
print(cols)

Index(['food', 'Caloric Value', 'Fat', 'Saturated Fats',
       'Monounsaturated Fats', 'Polyunsaturated Fats', 'Carbohydrates',
       'Sugars', 'Protein', 'Dietary Fiber', 'Cholesterol', 'Sodium', 'Water',
       'Vitamin A', 'Vitamin B1', 'Vitamin B11', 'Vitamin B12', 'Vitamin B2',
       'Vitamin B3', 'Vitamin B5', 'Vitamin B6', 'Vitamin C', 'Vitamin D',
       'Vitamin E', 'Vitamin K', 'Calcium', 'Copper', 'Iron', 'Magnesium',
       'Manganese', 'Phosphorus', 'Potassium', 'Selenium', 'Zinc',
       'Nutrition Density'],
      dtype='str')

In [17]:
food_data_pt = food_data.copy()
for col in cols:
    translated_col = translate_to_portuguese(col)
    print(f"Translating column '{col}' to '{translated_col}'")
    food_data_pt.rename(columns={col: translated_col}, inplace=True)
    #print(f"Column '{col}' renamed to '{translated_col}'")

Translating column 'food' to 'Alimento.'
Translating column 'Caloric Value' to 'Valor Calórico.'
Translating column 'Fat' to 'Gordura.'
Translating column 'Saturated Fats' to 'Gorduras Saturadas.'
Translating column 'Monounsaturated Fats' to 'Ácidos Monounsaturogênicos.'
Translating column 'Polyunsaturated Fats' to 'Gorduras Poliinsaturadas.'
Translating column 'Carbohydrates' to 'Hidratos de Carbono.'
Translating column 'Sugars' to ' Açúcares.'
Translating column 'Protein' to 'Proteína.'
Translating column 'Dietary Fiber' to 'Fibra Alimentar.'
Translating column 'Cholesterol' to 'Colesterol.'
Translating column 'Sodium' to 'Potássio.'
Translating column 'Water' to 'Água.'
Translating column 'Vitamin A' to 'Vitamina A.'
Translating column 'Vitamin B1' to 'Vitamina B1.'
Translating column 'Vitamin B11' to 'Vitamina B12.'
Translating column 'Vitamin B12' to 'Vitamina B12.'
Translating column 'Vitamin B2' to 'Vitamina B2.'
Translating column 'Vitamin B3' to 'Vitamina B3.'
Translating column 'Vitamin B5' to 'Vitamina B5.'
Translating column 'Vitamin B6' to 'Vitamina B6.'
Translating column 'Vitamin C' to 'Vitamina C.'
Translating column 'Vitamin D' to 'Vitamina D.'
Translating column 'Vitamin E' to 'Vitamina E.'
Translating column 'Vitamin K' to 'Vitamina K.'
Translating column 'Calcium' to 'Cálcio.'
Translating column 'Copper' to 'Cobre.'
Translating column 'Iron' to 'Ferro.'
Translating column 'Magnesium' to 'Magnésio.'
Translating column 'Manganese' to 'Manganesa.'
Translating column 'Phosphorus' to 'Fósforo.'
Translating column 'Potassium' to 'Potássio.'
Translating column 'Selenium' to 'Selenium.'
Translating column 'Zinc' to 'Zinco.'
Translating column 'Nutrition Density' to 'Densidade Nutricional.'

In [29]:
food_data_pt.head(5)

,Alimento,Valor Calórico,Gordura,Gorduras Saturadas,Gordura MonoSaturada,Gorduras Poliinsaturadas,Hidratos de Carbono,Açúcares,Proteína,Fibra,...,Cálcio,Cobre,Ferro,Magnésio,Manganês,Fósforo,Potássio,Selénio,Zinco,Densidade Nutricional
0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [19]:
for col in food_data_pt.columns:
    # eliminate periods from column names
    new_col_name = col.replace('.', '')
    food_data_pt.rename(columns={col: new_col_name}, inplace=True)

In [28]:
food_data_pt.columns

Index(['Alimento', 'Valor Calórico', 'Gordura', 'Gorduras Saturadas',
       'Gordura MonoSaturada', 'Gorduras Poliinsaturadas',
       'Hidratos de Carbono', ' Açúcares', 'Proteína', 'Fibra', 'Colesterol',
       'Potássio', 'Água', 'Vitamina A', 'Vitamina B1', 'Vitamina B12',
       'Vitamina B12', 'Vitamina B2', 'Vitamina B3', 'Vitamina B5',
       'Vitamina B6', 'Vitamina C', 'Vitamina D', 'Vitamina E', 'Vitamina K',
       'Cálcio', 'Cobre', 'Ferro', 'Magnésio', 'Manganês', 'Fósforo',
       'Potássio', 'Selénio', 'Zinco', 'Densidade Nutricional'],
      dtype='str')

In [30]:
food_data_pt.head()

,Alimento,Valor Calórico,Gordura,Gorduras Saturadas,Gordura MonoSaturada,Gorduras Poliinsaturadas,Hidratos de Carbono,Açúcares,Proteína,Fibra,...,Cálcio,Cobre,Ferro,Magnésio,Manganês,Fósforo,Potássio,Selénio,Zinco,Densidade Nutricional
0,cream cheese,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,neufchatel cheese,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,requeijao cremoso light catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,ricotta cheese,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,cream cheese low fat,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [31]:
for index, row in food_data_pt.iterrows():
    description = row['Alimento']
    translated_description = translate_to_portuguese(description)
    print(f"Translating food description '{description}' to '{translated_description}'")
    food_data_pt.at[index, 'food'] = translated_description

Translating food description 'cream cheese' to 'Queijo cremoso.'
Translating food description 'neufchatel cheese' to 'Queijo Neufchâtel.'
Translating food description 'requeijao cremoso light catupiry' to 'Requeijão cremoso light Catupiry.'
Translating food description 'ricotta cheese' to 'Queijo ricotta.'
Translating food description 'cream cheese low fat' to 'Queijo cremoso baixo em gordura.'
Translating food description 'cream cheese fat free' to 'Queijo cremoso sem gordura.'
Translating food description 'gruyere cheese' to 'Queijo Gruyère.'
Translating food description 'cheddar cheese' to 'Queijo cheddar.'
Translating food description 'parmesan cheese' to 'Queijo parmesano.'
Translating food description 'romano cheese' to 'Queijo romano.'
Translating food description 'parmesan cheese grated' to 'Queijo parmesão ralado.'
Translating food description 'port salut cheese' to 'Queijo Port Salut.'
Translating food description 'swiss cheese' to 'Queijo suíço.'
Translating food description 'goat cheese hard' to 'Queijo de cabra duro.'
Translating food description 'gouda cheese' to 'Queijo Gouda.'
Translating food description 'pepper jack cheese lucerne' to 'Queijo caseiro de pimenta e lucerna.'
Translating food description 'caraway cheese' to 'Queijo de caril.'
Translating food description 'gjetost cheese' to 'Queijo gjetost.'
Translating food description 'tilsit cheese' to 'Queijo tilsit.'
Translating food description 'goat cheese' to 'Queijo de cabra.'
Translating food description 'brick cheese' to 'Queijo de tijolo.'
Translating food description 'asadero cheese' to 'Queijo Asadero.'
Translating food description 'camembert cheese' to 'Queijo Camembert.'
Translating food description 'provolone cheese reduced fat' to 'Queijo Provolone reduzido em gordura.'
Translating food description 'roquefort cheese' to 'Queijo Roquefort.'
Translating food description 'queso blanco cheese' to 'Queijo branco.'
Translating food description 'queso seco cheese' to 'Queijo seco.'
Translating food description 'goat cheese soft' to 'Queijo de cabra suave.'
Translating food description 'mozzarella cheese' to 'Queijo mozzarella.'
Translating food description 'chihuahua cheese' to 'Queijo de Chihuahua.'
Translating food description 'limburger cheese' to 'Queijo Limburger.'
Translating food description 'muenster cheese' to 'Queijo muenster.'
Translating food description 'queso fresco cheese' to 'Queijo fresco.'
Translating food description 'brie cheese' to 'Queijo brie.'
Translating food description 'pimento cheese' to 'Queijo com pimento.'
Translating food description 'mexican cheese' to 'Queijo mexicano.'
Translating food description 'feta cheese' to 'Queijo feta.'
Translating food description 'mozzarella cheese fat free' to 'Queijo mozzarella sem gordura.'
Translating food description 'provolone cheese' to 'Queijo Provolone.'
Translating food description 'anejo cheese' to 'Queijo Añejo.'
Translating food description 'honey' to 'Mel.'
Translating food description 'apple butter' to 'Manteiga de maçã.'
Translating food description 'fruit jam' to 'Marmelada de frutas.'
Translating food description 'chocolate hazelnut spread' to 'Pulverização de chocolate e noz.'
Translating food description 'peanut butter' to 'Manteiga de amendoim.'
Translating food description 'peanut spread' to 'Pasta de amendoim.'
Translating food description 'chicken spread' to 'Pão de frango.'
Translating food description 'cheese spread' to 'Purinho para queijo.'
Translating food description 'tahini' to 'Tahini.'
Translating food description 'orange marmalade' to 'Marmalade de laranja.'
Translating food description 'american cheese spread' to 'Sorvetão de queijo americano.'
Translating food description 'apricot jam' to 'Marmelada de damasco.'
Translating food description 'chunky peanut butter' to 'Manteiga de amendoim grossa.'
Translating food description 'ham and cheese spread' to 'Purê de presunto e queijo.'
Translating food description 'chicken and rice casserole homade' to 'Arroz e creme de frango caseiro.'
Translating food description 'picnic loaf' to 'Pão de picnic.'
Translating food description 'corn tamale' to 'Tamales de milho.'
Translating food description 'baked potato with cheese sauce bacon' to 'Batata assada com molho de queijo e bacon.'
Translating food description 'chinese egg roll' to 'Rolinho chinês.'
Translating food description 'butter croissant' to 'Croissant com manteiga.'
Translating food description 'enchilada with cheese beef' to 'Enchilada com queijo e carne de boi.'
Translating food description 'corned beef hash with potatoes' to 'Arroz de carne enlatada com batata.'
Translating food description 'biscuit with egg cheese bacon' to 'Biscoito com ovo, queijo e bacon.

(Note: I kept the translation concise and literal, as per your request. If you'd like me to rephrase or provide more context, please let me know!)'
Translating food description 'bagel with ham egg cheese' to 'Bagel com ham, ovos e queijo.'
Translating food description 'quesadilla with chicken' to 'Quixotada com frango.'
Translating food description 'corn rice' to 'Arroz de milho.'
Translating food description 'kung pao chicken' to 'Churrasco de kung pao.'
Translating food description 'beef empanada' to 'Empadinha de carne de boi.'
Translating food description 'frijoles with cheese' to 'Frijoles com queijo.'
Translating food description 'burrito with beef' to '"Burrito com carne de boi."'
Translating food description 'crispy chicken sandwich' to 'Sanduíche de frango crocante.'
Translating food description 'enchilada with cheese' to 'Enchilada com queijo.'
Translating food description 'pork egg roll' to 'Rolo de porco e ovo.'
Translating food description 'corn on the cob with butter' to 'Milho no tigela com manteiga.'
Translating food description 'pancakes with butter syrup' to 'Pancakes com sírup de manteiga.'
Translating food description 'burrito with beans' to 'Burrito com feijão.'
Translating food description 'scrambled eggs' to 'Ovos mexidos.'
Translating food description 'baked potato with sour cream' to 'Patata assada com creme azeda.'
Translating food description 'turkey and gravy' to 'Turquia e molho.'
Translating food description 'chicken egg roll' to 'Pão de ovo de frango.'
Translating food description 'vegetable egg roll' to 'Rolinho de vegetal.'
Translating food description 'ham cheese roll' to 'Pão com hams e queijo.'
Translating food description 'biscuit with ham' to 'Biscoito com presunto.'
Translating food description 'lemon chicken' to 'Frango com limão.'
Translating food description 'hummus' to 'Aguardente.'
Translating food description 'croissant with egg cheese' to 'Croissant com ovo e queijo.'
Translating food description 'enchirito with cheese beef beans' to 'Enchilada com queijo, carne e feijão.'
Translating food description 'sweet sour pork' to 'Carne de porco com sabor doce e ácido.'
Translating food description 'crab cake' to 'Torta de guelra.'
Translating food description 'egg dinner roll' to 'Pão de jantar com ovos.'
Translating food description 'english muffin with egg cheese sausage' to 'Pão inglês com ovos, queijo e linguiça.'
Translating food description 'buttermilk pancakes' to 'Pancakes de manteiga.'
Translating food description 'omelet' to 'Omelete.'
Translating food description 'taco with chicken cheese lettuce' to 'Taco com frango, queijo, alface.'
Translating food description 'spinach souffle' to 'Soufflé de espinafre.'
Translating food description 'english muffin with cheese sausage' to 'Pão inglês com salsicha queijo.'
Translating food description 'potato gratin' to 'Gratin de batata.'
Translating food description 'biscuit with egg' to 'Biscoito com ovo.'
Translating food description 'french fries deep fried' to 'Fritas francesas assadas.'
Translating food description 'sweet sour chicken' to 'Frango-doce-ácido.'
Translating food description 'burrito with beans beef' to 'Burrito com feijão e carne de boi.'
Translating food description 'nachos with cinnamon sugar' to 'Nachos com açúcar e canela.'
Translating food description 'arroz con grandules' to 'Arroz com amendoins.'
Translating food description 'chili con carne' to 'Chili con carne.'
Translating food description 'arroz con abichuelas' to 'Arroz com feijões.'
Translating food description 'biscuit with sausage' to 'Biscoito com linguiça.'
Translating food description 'vegetarian stew' to 'Sopa vegetariana.'
Translating food description 'chicken sandwich with cheese' to 'Sanduíche de frango com queijo.'
Translating food description 'biscuit with egg steak' to 'Biscoito com ovos e estofado.'
Translating food description 'taco salad' to 'Salada de taco.'
Translating food description 'succotash' to 'Succotash.'
Translating food description 'nachos with cheese jalapeno peppers' to 'Nachos com queijo e pimenta jalapeño.'
Translating food description 'biscuit with egg ham' to 'Biscoito com ovo e presunto.'
Translating food description 'ladyfingers' to 'Palmieras.'
Translating food description 'mozzarella steak fried' to '"Estekiada de queijo mozzarella frita."'
Translating food description 'tamale navajo' to 'Tamale navajo.'
Translating food description 'blueberry pancakes' to 'Pancas de aveia com blueberry.'
Translating food description 'chimichanga with beef cheese' to 'Chimichanga com carne e queijo.'
Translating food description 'egg cheese sandwich' to 'Sanduíche de ovo e queijo.'
Translating food description 'biscuit with egg bacon' to 'Biscoito com ovo e bacon.'
Translating food description 'pupusas con queso' to 'Pupasas com queijo.'
Translating food description 'apple croissant' to 'Croissant de maçã.'
Translating food description 'refried red beans' to 'Frijoles roxos refogeados.'
Translating food description 'tostada with guacamole' to 'Tostada com guacamole.'
Translating food description 'chicken sandwich' to 'Sanduíche de frango.'
Translating food description 'fried rice' to 'Arroz frito.'
Translating food description 'pupusas del cerdo' to 'Pupasas do porco.'
Translating food description 'turkey pot pie' to 'Tartaruga de pot pie.'
Translating food description 'cheese croissant' to 'Pão croissant com queijo.'
Translating food description 'chimichanga with beef' to 'Chimichanga com carne.'
Translating food description 'french toast with butter' to 'Pão Francês com manteiga.'
Translating food description 'ham egg cheese sandwich' to 'Sanduíche de ham, ovos e queijo.'
Translating food description 'english muffin with butter' to 'Pão inglês com manteiga.'
Translating food description 'savoury noodle one pan dinner tandaco' to 'Jantar de massa salgada à prova de um prato único Tandaco.'
Translating food description 'ham cheese sandwich' to 'Sanduíche de hams e queijo.'
Translating food description 'sweet gefilte fish' to 'Peixe gefilte doce.'
Translating food description 'poached egg' to 'Ovo poché.'
Translating food description 'tostada with beef cheese' to 'Tostada com carne e queijo.'
Translating food description 'tostada with beans cheese' to 'Tostada com feijão e queijo.'
Translating food description 'pork tamale' to 'Tamales de porco.'
Translating food description 'nachos with cheese' to 'Nachos com queijo.'
Translating food description 'pulled pork in barbecue sauce' to 'Carne de porco arrastada com molho de barbecue.'
Translating food description 'baked potato with cheese sauce' to 'Batata assada com molho de queijo.'
Translating food description 'baked beans' to 'Feijão enlatado.'
Translating food description 'arroz con frijoles' to 'Arroz com feijão.'
Translating food description 'taco with beef cheese lettuce' to 'Taco com carne, queijo e alface.'
Translating food description 'burrito with beans cheese beef' to 'Burrito com feijão, queijo e carne de bovino.'
Translating food description 'egg mix' to 'Mistura de ovo.'
Translating food description 'falafel' to 'Falafel.'
Translating food description 'taco salad with chili con carne' to 'Salada de taco com chili con carne.'
Translating food description 'wonton wrappers' to 'Tortellini de pão.'
Translating food description 'hushpuppies' to 'Hushpuppies.'
Translating food description 'chicken pot pie' to 'Torta de frango e vegetais.'
Translating food description 'general tsos chicken' to 'Frango Geral Tso.'
Translating food description 'burrito with beans cheese' to 'Burrito com feijão e queijo.'
Translating food description 'vegetarian fillets' to 'Filetes vegetarianos.'
Translating food description 'biscuit with egg sausage' to 'Biscoito com ovos e salsicha.'
Translating food description 'chicken chow mein' to 'Chow mein de frango.'
Translating food description 'fruit burrito' to 'Fruita burrito.'
Translating food description 'arroz con leche' to 'Arroz com leite.'
Translating food description 'caramel custard flan' to 'Flan de caramelo à creme.'
Translating food description 'gelatin dessert' to 'Doce de gelatina.'
Translating food description 'chocolate milk dessert' to 'Sorvetinho de leite com chocolate.'
Translating food description 'chocolate mousse' to 'Mousse de chocolate.'
Translating food description 'dulce de leche' to 'Dulce de leche.'
Translating food description 'apple crisp' to 'Crúpula de maçã.'
Translating food description 'spinach spaghetti cooked' to 'Espinafre spaghetti cozido.'
Translating food description 'corn pasta cooked' to 'Pasta de milho cozida.'
Translating food description 'spaghetti with meat sauce' to 'Espaguete com molho de carne.'
Translating food description 'pasta with meatballs in tomato sauce' to 'Pasta com alcatras em molho de tomate.'
Translating food description 'cheese tortellini' to 'Tortellini de queijo.'
Translating food description 'pasta with sliced franks in tomato sauce' to 'Pasta com linguiças cortadas em molho de tomate.'
Translating food description 'lasagna' to 'Lasanha.'
Translating food description 'macaroni cheese' to 'Macarrão quente com queijo.'
Translating food description 'vegetable lasagna' to 'Lasanha de vegetais.'
Translating food description 'spinach egg noodles cooked' to 'Espinafre com macarrão cozido.'
Translating food description 'cheese lasagna' to 'Lasanha de queijo.'
Translating food description 'pasta with tomato sauce' to 'Macarrão com molho de tomate.'
Translating food description 'spinach pasta cooked' to 'Macarrão com espinafre cozido.'
Translating food description 'vegetable chicken soup' to 'Sopa de frango com vegetais.'
Translating food description 'bean ham soup' to 'Sopa de feijão com presunto.'
Translating food description 'cream of chicken soup' to 'Sopa de creme de frango.'
Translating food description 'tomato soup canned' to 'Sopa de tomate enlatada.'
Translating food description 'egg drop soup' to 'Sopa de ovo e gotas.'
Translating food description 'scotch broth' to 'Sopa Escocesa.'
Translating food description 'cream of onion soup' to 'Sopa de creme de cebola.'
Translating food description 'chicken broth dry' to 'Caldo de frango seco.'
Translating food description 'vegetable soup with beef broth' to 'Sopa de legumes com caldo de carne de boi.'
Translating food description 'chili with beans canned' to 'Chile com feijão enlatado.'
Translating food description 'beef noodle soup' to 'Sopa de carne e macarrão.'
Translating food description 'consomme dry' to 'Consomme seco.'
Translating food description 'chicken mushroom soup' to 'Sopa de frango e cogumelo.'
Translating food description 'beef vegetable soup' to 'Sopa de carne e vegetais.'
Translating food description 'black bean soup' to 'Sopa de feijão preto.'
Translating food description 'split pea soup with ham bacon' to 'Sopa de ervilhas com ham e bacon.'
Translating food description 'cream of mushroom soup' to 'Sopa de creme de cogumelo.'
Translating food description 'green pea soup' to 'Sopa de ervilha verde.'
Translating food description 'chicken broth soup' to 'Sopa de caldo de frango.'
Translating food description 'chicken mushroom chowder soup' to 'Sopa de chowder de frango com cogumelo.'
Translating food description 'chicken dumplings soup' to 'Sopa de frango com manteiga.'
Translating food description 'chicken vegetable soup' to 'Sopa de frango e legumes.'
Translating food description 'turkey vegetable soup' to 'Sopa de galinha com vegetais.'
Translating food description 'wonton soup' to 'Sopa de wonton.'
Translating food description 'beef stock' to 'Caldo de carne.'
Translating food description 'mushroom barley soup' to 'Sopa de cogumelo e cevada.'
Translating food description 'gazpacho soup' to 'Sopa de gazpacho.'
Translating food description 'beef mushroom soup' to 'Sopa de carne e cogumelo.'
Translating food description 'chicken rice soup' to 'Sopa de frango com arroz.'
Translating food description 'pepperpot soup' to 'Sopa de pepperpot.'
Translating food description 'vegetable soup' to 'Sopa de legumes.'
Translating food description 'chili beef soup' to 'Sopa de chili com carne.'
Translating food description 'chicken soup' to 'Sopa de frango.'
Translating food description 'bean with frankfurters soup' to 'Sopa de feijão com frankfurters.'
Translating food description 'pea soup' to 'Sopa de ervilha.'
Translating food description 'turkey soup' to 'Sopa de peru.'
Translating food description 'stockpot soup' to 'Sopa de caldeirão.'
Translating food description 'hot sour soup' to 'Sopa quente e ácida.'
Translating food description 'cheese soup' to 'Sopa de queijo.'
Translating food description 'cream of potato soup' to 'Sopa de creme de batata.'
Translating food description 'bean with bacon soup' to 'Sopa de feijão com bacon.'
Translating food description 'fish stock' to 'Sopa de peixe.'
Translating food description 'split pea soup with ham' to 'Sopa de ervilhas com presunto.'
Translating food description 'beef broth soup' to 'Sopa de caldo de carne.'
Translating food description 'lentil soup with ham' to 'Sopa de lentilhas com presunto.'
Translating food description 'tomato soup' to 'Sopa de tomate.'
Translating food description 'fish broth' to 'Caldo de peixe.'
Translating food description 'chili without beans canned' to 'Chili sem feijão em lata.'
Translating food description 'minestrone soup' to 'Sopa de minestrone.'
Translating food description 'clam chowder soup' to 'Sopa de chowder de almeja.'
Translating food description 'tomato vegetable soup' to 'Sopa de vegetais com tomate.'
Translating food description 'cream of rice coup' to 'Creme de arroz calórico.'
Translating food description 'cream of celery soup' to 'Sopa de creme de cebola.'
Translating food description 'chicken gravy' to 'Sugo de frango.'
Translating food description 'tomato rice soup' to 'Sopa de arroz com tomate.'
Translating food description 'vegetable beef soup' to 'Sopa de vegetais com carne.'
Translating food description 'tomato beef noodle soup' to 'Sopa de tomate com carne e macarrão.'
Translating food description 'oyster stew soup' to 'Sopa de tarta de ostra.'
Translating food description 'ramen noodle soup dry' to 'Sopa de noodles de ramen seco.'
Translating food description 'chicken noodle soup' to 'Sopa de frango com massa.'
Translating food description 'chicken bouillon dry' to 'Caldo de frango seco.'
Translating food description 'cream of asparagus soup' to 'Sopa de creme de aspargo.'
Translating food description 'turkey noodle soup' to 'Sopa de frango com macarrão.'
Translating food description 'cream of shrimp soup' to 'Sopa de creme de camarão.'
Translating food description 'bean with pork soup' to 'Sopa de feijão com carne de porco.'
Translating food description 'chicken broth' to 'Caldo de frango.'
Translating food description 'beef broth powder' to 'Pó de caldo de carne.'
Translating food description 'split pea soup' to 'Sopa de ervilhas partidas.'
Translating food description 'escarole soup' to 'Sopa de escarole.'
Translating food description 'chicken stock' to 'Caldo de frango.'
Translating food description 'tomato bisque soup' to 'Sopa de tomate bisque.'
Translating food description 'shark fin soup' to 'Sopa de aleta de tubarão.'
Translating food description 'onion soup' to 'Sopa de cebola.'

In [32]:
for index, row in food_data_pt.iterrows():
    description = row['food']
    #translated_description = translate_to_portuguese(description)
    #print(f"Translating food description '{description}' to '{translated_description}'")
    food_data_pt.at[index, 'Alimento'] = description

food_data_pt.drop(columns=['food'], inplace=True)

In [34]:
for index, row in food_data_pt.iterrows():
    description = row['Alimento']
    description = description.replace(".", "")
    #print(f"Removing periods from food description '{row['Alimento']}' to '{description}'")
    food_data_pt.at[index, 'Alimento'] = description
food_data_pt.head()

,Alimento,Valor Calórico,Gordura,Gorduras Saturadas,Gordura MonoSaturada,Gorduras Poliinsaturadas,Hidratos de Carbono,Açúcares,Proteína,Fibra,...,Cálcio,Cobre,Ferro,Magnésio,Manganês,Fósforo,Potássio,Selénio,Zinco,Densidade Nutricional
0,Queijo cremoso,51,5.0,2.9,1.3,0.200,0.8,0.500,0.9,0.0,...,0.008,14.100,0.082,0.027,1.300,0.091,15.5,19.100,0.039,7.070
1,Queijo Neufchâtel,215,19.4,10.9,4.9,0.800,3.1,2.700,7.8,0.0,...,99.500,0.034,0.100,8.500,0.088,117.300,129.2,0.054,0.700,130.100
2,Requeijão cremoso light Catupiry,49,3.6,2.3,0.9,0.000,0.9,3.400,0.8,0.1,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.000,5.400
3,Queijo ricotta,30,2.0,1.3,0.5,0.002,1.5,0.091,1.5,0.0,...,0.097,41.200,0.097,0.096,4.000,0.024,30.8,43.800,0.035,5.196
4,Queijo cremoso baixo em gordura,30,2.3,1.4,0.6,0.042,1.2,0.900,1.2,0.0,...,22.200,0.072,0.008,1.200,0.098,22.800,37.1,0.034,0.053,27.007

In [35]:
food_data_pt.to_csv(DATA_FOLDER + "/FOOD-DATA-FINAL-PT.csv", index=False)

# Add to dataset

In [33]:
import numpy as np
import pandas as pd


def add_food(df: pd.DataFrame, alimento: str, **kwargs) -> pd.DataFrame:
    """Add a food to the dataset. Only 'alimento' is required.

    Nutrient values are passed via a dict (columns have spaces/accents):
        df = add_food(df, "Banana", **{"Valor Calórico": 89, "Proteína": 1.1})
    Missing columns are filled with NaN.
    """
    alimento = alimento.strip()

    # Reject duplicates (case-insensitive)
    if df["Alimento"].str.strip().str.lower().eq(alimento.lower()).any():
        raise ValueError(f"'{alimento}' already exists in the dataset.")

    # Reject unknown columns (catches typos)
    unknown = set(kwargs) - set(df.columns)
    if unknown:
        raise KeyError(f"Unknown columns: {sorted(unknown)}")

    row = {col: np.nan for col in df.columns}
    row.update(kwargs)
    row["Alimento"] = alimento

    return pd.concat([df, pd.DataFrame([row])], ignore_index=True)

# Save Meal

In [ ]:
import json
import os
import pandas as pd

REFEICOES_CSV = "refeicoes.csv"
NAO_SOMAVEIS = ["Alimento", "Densidade Nutricional"]  # identificador e score, não somam


def criar_dataset_refeicoes(food_data_df: pd.DataFrame) -> pd.DataFrame:
    nutrientes = [c for c in food_data_df.columns if c not in NAO_SOMAVEIS]
    return pd.DataFrame(columns=["Nome da refeição", "Alimentos"] + nutrientes)


def carregar_refeicoes(food_data_df: pd.DataFrame, path: str = REFEICOES_CSV) -> pd.DataFrame:
    if os.path.exists(path):
        df = pd.read_csv(path)
        df["Alimentos"] = df["Alimentos"].apply(json.loads)  # str -> lista
        return df
    return criar_dataset_refeicoes(food_data_df)


def add_refeicao(df_ref: pd.DataFrame, food_data_df: pd.DataFrame, nome_refeicao: str,
                 alimentos: list[tuple[str, float]], path: str = REFEICOES_CSV) -> pd.DataFrame:
    """alimentos: lista de (nome, quantidade em gramas).

    df_ref = add_refeicao(df_ref, food_data_df, "Almoço",
                          [("Arroz", 150), ("Frango", 120)])
    """
    nutrientes = [c for c in df_ref.columns if c not in ("Nome da refeição", "Alimentos")]

    base = food_data_df.copy()
    base.index = base["Alimento"].str.strip().str.lower()
    base = base[nutrientes].apply(pd.to_numeric, errors="coerce")

    parcelas = []
    for nome, qtd in alimentos:
        chave = nome.strip().lower()
        if chave not in base.index:
            raise KeyError(f"'{nome}' não existe no food_data_df.")
        parcelas.append(base.loc[chave] * qtd / 100)  # valores por 100 g

    totais = pd.DataFrame(parcelas).sum(min_count=1)  # NaN só se ninguém tiver o valor

    linha = {"Nome da refeição": nome_refeicao.strip(), "Alimentos": alimentos, **totais.to_dict()}
    df_ref = pd.concat([df_ref, pd.DataFrame([linha])], ignore_index=True)

    guardar = df_ref.copy()
    guardar["Alimentos"] = guardar["Alimentos"].apply(json.dumps)  # lista -> str para o CSV
    guardar.to_csv(path, index=False)
    return df_ref

# Calculate TMB and calories to consume

To calculate your BMR/RMR using the Mifflin-St. Jeor equationTrusted Source, you’ll need to use one of two equations:

- Males: 10 × weight (in kilograms) + 6.25 × height (in centimeters) – 5 × age (in years) + 5
- Females: 10 × weight (in kilograms) + 6.25 × height (in centimeters) – 5 × age (in years) – 161

In [ ]:
def calculate_bmr(weight, height, age, gender):
    """
    Calculate Basal Metabolic Rate (BMR) using the Mifflin-St Jeor Equation.
    
    Parameters:
    weight (float): Weight in kilograms
    height (float): Height in centimeters
    age (int): Age in years
    gender (str): 'male' or 'female'

    Returns:
    float: BMR value
    """

    if gender.lower() == 'male':
        bmr = 10 * weight + 6.25 * height - 5 * age + 5
    elif gender.lower() == 'female':
        bmr = 10 * weight + 6.25 * height - 5 * age - 161
    else:
        raise ValueError("Gender must be 'male' or 'female'")

    return bmr

To calculate your TDEE, you’ll need to add an activity factor to the equation:

- 1.2: sedentary (little to no exercise)
- 1.375: lightly active (light exercise 1 to 3 days per week)
- 1.55: moderately active (moderate exercise 6 to 7 days per week)
- 1.725: very active (hard exercise every day, or exercising twice a day)
- 1.9: extra active (very hard exercise, training, or a physical job)

Then, you can calculate your TDEE using this equation:

TDEE = BMR x activity factor

In [ ]:
def calculate_tde(bmr, activity_level):
    """
    Calculate Total Daily Energy Expenditure (TDEE) based on BMR and activity level.
    
    Parameters:
    bmr (float): Basal Metabolic Rate
    activity_level (str): One of the following - 'sedentary', 'lightly active', 'moderately active', 'very active', 'extra active'

    Returns:
    float: TDEE value
    """

    activity_multipliers = {
        'sedentary': 1.2,
        'lightly active': 1.375,
        'moderately active': 1.55,
        'very active': 1.725,
        'extra active': 1.9
    }

    if activity_level not in activity_multipliers:
        raise ValueError("Activity level must be one of the following: " + ", ".join(activity_multipliers.keys()))

    tde = bmr * activity_multipliers[activity_level]
    return tde

In [ ]:
def calorie_deficit(tdee, deficit=400):
    """for weight loss, a common recommendation is to create a calorie deficit of 400-500 calories per day. This function calculates the target daily caloric intake for weight loss based on the provided TDEE."""
    return tdee - deficit

# Track Progress

# Track Water

# Interactive App